export const Types = [
  {
    title: "Bug",
    path: "/bug",
    cName: "sidebar-options",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3c/Pok%C3%A9mon_Bug_Type_Icon.svg",
    color: "83c400",
  },
  {
    title: "Dark",
    path: "/dark",
    cName: "sidebar-options",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/09/Pok%C3%A9mon_Dark_Type_Icon.svg",
    color: "5a5366",
  },
  {
    title: "Dragon",
    path: "/dragon",
    cName: "sidebar-options",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Pok%C3%A9mon_Dragon_Type_Icon.svg",
    color: "0070ca",
  },
  {
    title: "Electric",
    path: "/electric",
    cName: "sidebar-options",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Pok%C3%A9mon_Electric_Type_Icon.svg",
    color: "fbd200",
  },
  {
    title: "Fairy",
    path: "/fairy",
    cName: "sidebar-options",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/08/Pok%C3%A9mon_Fairy_Type_Icon.svg",
    color: "fb8aec",
  },
  {
    title: "Fighting",
    path: "/fighting",
    cName: "sidebar-options",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/be/Pok%C3%A9mon_Fighting_Type_Icon.svg",
    color: "e12c6a",
  },
  {
    title: "Fire",
    path: "/fire",
    cName: "sidebar-options",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/56/Pok%C3%A9mon_Fire_Type_Icon.svg",
    color: "ff983e",
  },
  {
    title: "Flying",
    path: "/flying",
    cName: "sidebar-options",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Pok%C3%A9mon_Flying_Type_Icon.svg",
    color: "8aace3",
  },
  {
    title: "Ghost",
    path: "/ghost",
    cName: "sidebar-options",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Pok%C3%A9mon_Ghost_Type_Icon.svg",
    color: "4a6ab3",
  },
  {
    title: "Grass",
    path: "/grass",
    cName: "sidebar-options",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Pok%C3%A9mon_Grass_Type_Icon.svg",
    color: "33c049",
  },
  {
    title: "Ground",
    path: "/ground",
    cName: "sidebar-options",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8d/Pok%C3%A9mon_Ground_Type_Icon.svg",
    color: "e97233",
  },
  {
    title: "Ice",
    path: "/ice",
    cName: "sidebar-options",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/88/Pok%C3%A9mon_Ice_Type_Icon.svg",
    color: "4ad2c1",
  },
  {
    title: "Normal",
    path: "/normal",
    cName: "sidebar-options",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/aa/Pok%C3%A9mon_Normal_Type_Icon.svg",
    color: "929ba4",
  },
  {
    title: "Poison",
    path: "/poison",
    cName: "sidebar-options",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Pok%C3%A9mon_Poison_Type_Icon.svg",
    color: "b767ce",
  },
  {
    title: "Psychic",
    path: "/psychic",
    cName: "sidebar-options",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Pok%C3%A9mon_Psychic_Type_Icon.svg",
    color: "ff6676",
  },
  {
    title: "Rock",
    path: "/rock",
    cName: "sidebar-options",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bb/Pok%C3%A9mon_Rock_Type_Icon.svg",
    color: "c9b787",
  },
  {
    title: "Steel",
    path: "/steel",
    cName: "sidebar-options",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/38/Pok%C3%A9mon_Steel_Type_Icon.svg",
    color: "5a8fa3",
  },
  {
    title: "Water",
    path: "/water",
    cName: "sidebar-options",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Pok%C3%A9mon_Water_Type_Icon.svg",
    color: "3293dd",
  },
];
